// Updated country and language data from Google Ads API

export const COUNTRIES = [
  {"code":"US", "locationId":2840, "name":"United States"},
  {"code":"CA", "locationId":2124, "name":"Canada"},
  {"code":"MX", "locationId":2484, "name":"Mexico"},
  {"code":"GB", "locationId":2826, "name":"United Kingdom"},
  {"code":"DE", "locationId":2276, "name":"Germany"},
  {"code":"FR", "locationId":2250, "name":"France"},
  {"code":"IT", "locationId":2380, "name":"Italy"},
  {"code":"ES", "locationId":2724, "name":"Spain"},
  {"code":"NL", "locationId":2528, "name":"Netherlands"},
  {"code":"SE", "locationId":2752, "name":"Sweden"},
  {"code":"NO", "locationId":2578, "name":"Norway"},
  {"code":"DK", "locationId":2208, "name":"Denmark"},
  {"code":"FI", "locationId":2246, "name":"Finland"},
  {"code":"CH", "locationId":2756, "name":"Switzerland"},
  {"code":"AT", "locationId":2040, "name":"Austria"},
  {"code":"BE", "locationId":2056, "name":"Belgium"},
  {"code":"IE", "locationId":2372, "name":"Ireland"},
  {"code":"PT", "locationId":2620, "name":"Portugal"},
  {"code":"PL", "locationId":2616, "name":"Poland"},
  {"code":"CZ", "locationId":2203, "name":"Czech Republic"},
  {"code":"HU", "locationId":2348, "name":"Hungary"},
  {"code":"GR", "locationId":2300, "name":"Greece"},
  {"code":"RO", "locationId":2642, "name":"Romania"},
  {"code":"BG", "locationId":2100, "name":"Bulgaria"},
  {"code":"HR", "locationId":2191, "name":"Croatia"},
  {"code":"SK", "locationId":2703, "name":"Slovakia"},
  {"code":"SI", "locationId":2705, "name":"Slovenia"},
  {"code":"LT", "locationId":2440, "name":"Lithuania"},
  {"code":"LV", "locationId":2428, "name":"Latvia"},
  {"code":"EE", "locationId":2233, "name":"Estonia"},
  {"code":"LU", "locationId":2442, "name":"Luxembourg"},
  {"code":"MT", "locationId":2470, "name":"Malta"},
  {"code":"CY", "locationId":2196, "name":"Cyprus"},
  {"code":"IS", "locationId":2352, "name":"Iceland"},
  {"code":"IN", "locationId":2356, "name":"India"},
  {"code":"CN", "locationId":2156, "name":"China"},
  {"code":"JP", "locationId":2392, "name":"Japan"},
  {"code":"KR", "locationId":2410, "name":"South Korea"},
  {"code":"AU", "locationId":2036, "name":"Australia"},
  {"code":"NZ", "locationId":2554, "name":"New Zealand"},
  {"code":"SG", "locationId":2702, "name":"Singapore"},
  {"code":"MY", "locationId":2458, "name":"Malaysia"},
  {"code":"TH", "locationId":2764, "name":"Thailand"},
  {"code":"VN", "locationId":2704, "name":"Vietnam"},
  {"code":"PH", "locationId":2608, "name":"Philippines"},
  {"code":"ID", "locationId":2360, "name":"Indonesia"},
  {"code":"HK", "locationId":2344, "name":"Hong Kong"},
  {"code":"TW", "locationId":2158, "name":"Taiwan"},
  {"code":"MO", "locationId":2446, "name":"Macau"},
  {"code":"PK", "locationId":2586, "name":"Pakistan"},
  {"code":"BD", "locationId":2050, "name":"Bangladesh"},
  {"code":"LK", "locationId":2144, "name":"Sri Lanka"},
  {"code":"NP", "locationId":2524, "name":"Nepal"},
  {"code":"BT", "locationId":2064, "name":"Bhutan"},
  {"code":"MV", "locationId":2462, "name":"Maldives"},
  {"code":"MN", "locationId":2496, "name":"Mongolia"},
  {"code":"KZ", "locationId":2398, "name":"Kazakhstan"},
  {"code":"UZ", "locationId":2860, "name":"Uzbekistan"},
  {"code":"KG", "locationId":2417, "name":"Kyrgyzstan"},
  {"code":"TJ", "locationId":2762, "name":"Tajikistan"},
  {"code":"TM", "locationId":2795, "name":"Turkmenistan"},
  {"code":"AF", "locationId":2004, "name":"Afghanistan"},
  {"code":"SA", "locationId":2682, "name":"Saudi Arabia"},
  {"code":"AE", "locationId":2784, "name":"UAE"},
  {"code":"QA", "locationId":2634, "name":"Qatar"},
  {"code":"KW", "locationId":2414, "name":"Kuwait"},
  {"code":"BH", "locationId":2048, "name":"Bahrain"},
  {"code":"OM", "locationId":2512, "name":"Oman"},
  {"code":"IL", "locationId":2376, "name":"Israel"},
  {"code":"TR", "locationId":2792, "name":"Turkey"},
  {"code":"IR", "locationId":2364, "name":"Iran"},
  {"code":"IQ", "locationId":2368, "name":"Iraq"},
  {"code":"JO", "locationId":2400, "name":"Jordan"},
  {"code":"LB", "locationId":2422, "name":"Lebanon"},
  {"code":"SY", "locationId":2760, "name":"Syria"},
  {"code":"YE", "locationId":2887, "name":"Yemen"},
  {"code":"ZA", "locationId":2710, "name":"South Africa"},
  {"code":"EG", "locationId":2818, "name":"Egypt"},
  {"code":"NG", "locationId":2566, "name":"Nigeria"},
  {"code":"KE", "locationId":2404, "name":"Kenya"},
  {"code":"GH", "locationId":2288, "name":"Ghana"},
  {"code":"TZ", "locationId":2834, "name":"Tanzania"},
  {"code":"UG", "locationId":2800, "name":"Uganda"},
  {"code":"RW", "locationId":2646, "name":"Rwanda"},
  {"code":"ET", "locationId":2231, "name":"Ethiopia"},
  {"code":"MA", "locationId":2504, "name":"Morocco"},
  {"code":"DZ", "locationId":2012, "name":"Algeria"},
  {"code":"TN", "locationId":2788, "name":"Tunisia"},
  {"code":"LY", "locationId":2434, "name":"Libya"},
  {"code":"SD", "locationId":2729, "name":"Sudan"},
  {"code":"ZW", "locationId":2716, "name":"Zimbabwe"},
  {"code":"BW", "locationId":2072, "name":"Botswana"},
  {"code":"NA", "locationId":2516, "name":"Namibia"},
  {"code":"ZM", "locationId":2894, "name":"Zambia"},
  {"code":"MW", "locationId":2454, "name":"Malawi"},
  {"code":"MZ", "locationId":2508, "name":"Mozambique"},
  {"code":"MG", "locationId":2450, "name":"Madagascar"},
  {"code":"MU", "locationId":2480, "name":"Mauritius"},
  {"code":"SC", "locationId":2690, "name":"Seychelles"},
  {"code":"BR", "locationId":2076, "name":"Brazil"},
  {"code":"AR", "locationId":2032, "name":"Argentina"},
  {"code":"CL", "locationId":2152, "name":"Chile"},
  {"code":"CO", "locationId":2170, "name":"Colombia"},
  {"code":"PE", "locationId":2604, "name":"Peru"},
  {"code":"VE", "locationId":2862, "name":"Venezuela"},
  {"code":"EC", "locationId":2218, "name":"Ecuador"},
  {"code":"BO", "locationId":2068, "name":"Bolivia"},
  {"code":"PY", "locationId":2600, "name":"Paraguay"},
  {"code":"UY", "locationId":2858, "name":"Uruguay"},
  {"code":"GY", "locationId":2328, "name":"Guyana"},
  {"code":"SR", "locationId":2740, "name":"Suriname"},
  {"code":"JM", "locationId":2388, "name":"Jamaica"},
  {"code":"CU", "locationId":2192, "name":"Cuba"},
  {"code":"DO", "locationId":2214, "name":"Dominican Republic"},
  {"code":"TT", "locationId":2780, "name":"Trinidad and Tobago"},
  {"code":"BB", "locationId":2052, "name":"Barbados"},
  {"code":"BS", "locationId":2044, "name":"Bahamas"},
  {"code":"BZ", "locationId":2084, "name":"Belize"},
  {"code":"CR", "locationId":2188, "name":"Costa Rica"},
  {"code":"PA", "locationId":2591, "name":"Panama"},
  {"code":"GT", "locationId":2320, "name":"Guatemala"},
  {"code":"HN", "locationId":2340, "name":"Honduras"},
  {"code":"SV", "locationId":2222, "name":"El Salvador"},
  {"code":"NI", "locationId":2558, "name":"Nicaragua"}
];

export const LANGUAGES = [
  { "languageId": 1000, "code": "en", "name": "English" },
  { "languageId": 1001, "code": "fr", "name": "French" },
  { "languageId": 1002, "code": "de", "name": "German" },
  { "languageId": 1003, "code": "es", "name": "Spanish" },
  { "languageId": 1004, "code": "it", "name": "Italian" },
  { "languageId": 1005, "code": "ja", "name": "Japanese" },
  { "languageId": 1006, "code": "nl", "name": "Dutch" },
  { "languageId": 1007, "code": "no", "name": "Norwegian" },
  { "languageId": 1008, "code": "pt", "name": "Portuguese" },
  { "languageId": 1009, "code": "ru", "name": "Russian" },
  { "languageId": 1010, "code": "sv", "name": "Swedish" },
  { "languageId": 1011, "code": "zh_CN", "name": "Chinese (Simplified)" },
  { "languageId": 1012, "code": "zh_TW", "name": "Chinese (Traditional)" },
  { "languageId": 1013, "code": "da", "name": "Danish" },
  { "languageId": 1014, "code": "fi", "name": "Finnish" },
  { "languageId": 1015, "code": "ko", "name": "Korean" },
  { "languageId": 1016, "code": "pl", "name": "Polish" },
  { "languageId": 1017, "code": "tr", "name": "Turkish" },
  { "languageId": 1018, "code": "cs", "name": "Czech" },
  { "languageId": 1019, "code": "el", "name": "Greek" },
  { "languageId": 1020, "code": "hu", "name": "Hungarian" },
  { "languageId": 1021, "code": "ro", "name": "Romanian" },
  { "languageId": 1022, "code": "sk", "name": "Slovak" },
  { "languageId": 1023, "code": "bg", "name": "Bulgarian" },
  { "languageId": 1024, "code": "hr", "name": "Croatian" },
  { "languageId": 1025, "code": "lt", "name": "Lithuanian" },
  { "languageId": 1026, "code": "lv", "name": "Latvian" },
  { "languageId": 1027, "code": "sl", "name": "Slovenian" },
  { "languageId": 1028, "code": "et", "name": "Estonian" },
  { "languageId": 1029, "code": "th", "name": "Thai" },
  { "languageId": 1030, "code": "uk", "name": "Ukrainian" },
  { "languageId": 1031, "code": "hi", "name": "Hindi" },
  { "languageId": 1032, "code": "he", "name": "Hebrew" },
  { "languageId": 1033, "code": "ar", "name": "Arabic" },
  { "languageId": 1034, "code": "ms", "name": "Malay" },
  { "languageId": 1035, "code": "id", "name": "Indonesian" },
  { "languageId": 1036, "code": "vi", "name": "Vietnamese" },
  { "languageId": 1037, "code": "tl", "name": "Filipino" },
  { "languageId": 1038, "code": "fa", "name": "Persian" },
  { "languageId": 1039, "code": "sr", "name": "Serbian" },
  { "languageId": 1040, "code": "eu", "name": "Basque" },
  { "languageId": 1041, "code": "ca", "name": "Catalan" },
  { "languageId": 1042, "code": "gl", "name": "Galician" },
  { "languageId": 1043, "code": "sw", "name": "Swahili" },
  { "languageId": 1044, "code": "af", "name": "Afrikaans" },
  { "languageId": 1045, "code": "az", "name": "Azerbaijani" },
  { "languageId": 1046, "code": "be", "name": "Belarusian" },
  { "languageId": 1047, "code": "ka", "name": "Georgian" },
  { "languageId": 1048, "code": "is", "name": "Icelandic" },
  { "languageId": 1049, "code": "kk", "name": "Kazakh" },
  { "languageId": 1050, "code": "ky", "name": "Kyrgyz" },
  { "languageId": 1051, "code": "mo", "name": "Moldovan" },
  { "languageId": 1052, "code": "mk", "name": "Macedonian" },
  { "languageId": 1053, "code": "mn", "name": "Mongolian" },
  { "languageId": 1054, "code": "uz", "name": "Uzbek" },
  { "languageId": 1055, "code": "hy", "name": "Armenian" },
  { "languageId": 1056, "code": "ne", "name": "Nepali" },
  { "languageId": 1057, "code": "pa", "name": "Punjabi" },
  { "languageId": 1058, "code": "si", "name": "Sinhala" },
  { "languageId": 1059, "code": "ta", "name": "Tamil" },
  { "languageId": 1060, "code": "te", "name": "Telugu" },
  { "languageId": 1061, "code": "ur", "name": "Urdu" },
  { "languageId": 1062, "code": "kn", "name": "Kannada" },
  { "languageId": 1063, "code": "ml", "name": "Malayalam" },
  { "languageId": 1064, "code": "gu", "name": "Gujarati" },
  { "languageId": 1065, "code": "mr", "name": "Marathi" },
  { "languageId": 1066, "code": "or", "name": "Odia" },
  { "languageId": 1067, "code": "as", "name": "Assamese" },
  { "languageId": 1068, "code": "bn", "name": "Bengali" },
  { "languageId": 1069, "code": "km", "name": "Khmer" },
  { "languageId": 1070, "code": "lo", "name": "Lao" },
  { "languageId": 1071, "code": "my", "name": "Burmese" },
  { "languageId": 1072, "code": "am", "name": "Amharic" },
  { "languageId": 1073, "code": "ps", "name": "Pashto" },
  { "languageId": 1074, "code": "sq", "name": "Albanian" },
  { "languageId": 1075, "code": "bh", "name": "Bihari" },
  { "languageId": 1076, "code": "bs", "name": "Bosnian" },
  { "languageId": 1077, "code": "ceb", "name": "Cebuano" },
  { "languageId": 1078, "code": "eo", "name": "Esperanto" },
  { "languageId": 1079, "code": "gd", "name": "Scottish Gaelic" },
  { "languageId": 1080, "code": "ha", "name": "Hausa" },
  { "languageId": 1081, "code": "haw", "name": "Hawaiian" },
  { "languageId": 1082, "code": "ig", "name": "Igbo" },
  { "languageId": 1083, "code": "zu", "name": "Zulu" },
  { "languageId": 1084, "code": "yi", "name": "Yiddish" },
  { "languageId": 1085, "code": "yo", "name": "Yoruba" },
  { "languageId": 1086, "code": "ht", "name": "Haitian Creole" },
  { "languageId": 1087, "code": "co", "name": "Corsican" },
  { "languageId": 1088, "code": "hmn", "name": "Hmong" },
  { "languageId": 1089, "code": "jw", "name": "Javanese" },
  { "languageId": 1090, "code": "la", "name": "Latin" },
  { "languageId": 1091, "code": "lb", "name": "Luxembourgish" },
  { "languageId": 1092, "code": "mi", "name": "Maori" },
  { "languageId": 1093, "code": "mt", "name": "Maltese" },
  { "languageId": 1094, "code": "ny", "name": "Chichewa" },
  { "languageId": 1095, "code": "so", "name": "Somali" },
  { "languageId": 1096, "code": "st", "name": "Sesotho" },
  { "languageId": 1097, "code": "su", "name": "Sundanese" },
  { "languageId": 1098, "code": "vo", "name": "Volapük" },
  { "languageId": 1099, "code": "wa", "name": "Walloon" },
  { "languageId": 1100, "code": "xh", "name": "Xhosa" }
];

export type Country = {
  code: string;
  locationId: number;
  name: string;
};

export type Language = {
  languageId: number;
  code: string;
  name: string;
};